# Generated by Django 4.2.7 on 2025-05-17 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Flight Number')),
                ('date', models.DateField(verbose_name='Flight Date')),
                ('etd', models.DateTimeField(verbose_name='Estimated Time of Departure')),
                ('eta', models.DateTimeField(verbose_name='Estimated Time of Arrival')),
                ('new_etd_eta', models.DateTimeField(blank=True, null=True, verbose_name='New ETD/ETA')),
                ('pax_count', models.PositiveIntegerField(default=0, verbose_name='Passenger Count')),
                ('passenger_mix', models.TextField(blank=True, verbose_name='Passenger Mix')),
                ('irops_type', models.CharField(choices=[('diversion', 'Diversion'), ('redispatch', 'Re-Dispatch'), ('delay', 'Delay'), ('cancellation', 'Cancellation'), ('other', 'Other')], default='delay', max_length=20, verbose_name='IROPS Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['-date', 'flight_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=200, verbose_name='Action Name')),
                ('assigned_team', models.CharField(max_length=100, verbose_name='Assigned Team')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Team Action',
                'verbose_name_plural': 'Team Actions',
                'ordering': ['status', 'action_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('team', models.CharField(choices=[('exec', 'Executive'), ('digital', 'Digital'), ('concierge', 'Concierge'), ('operations', 'Operations'), ('customer_service', 'Customer Service'), ('other', 'Other')], max_length=20, verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShuttleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuttle_a_time', models.DateTimeField(verbose_name='Shuttle A Time')),
                ('pickup_a', models.CharField(max_length=100, verbose_name='Pickup Location A')),
                ('shuttle_b_time', models.DateTimeField(blank=True, null=True, verbose_name='Shuttle B Time')),
                ('pickup_b', models.CharField(blank=True, max_length=100, verbose_name='Pickup Location B')),
                ('shuttle_company', models.CharField(max_length=100, verbose_name='Shuttle Company')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('driver_phone', models.CharField(max_length=20, verbose_name='Driver Phone')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shuttles', to='irops_app.flight', verbose_name='Flight')),
            ],
            options={
                'verbose_name': 'Shuttle Information',
                'verbose_name_plural': 'Shuttle Information',
                'ordering': ['flight', 'shuttle_a_time'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=10, unique=True, verbose_name='Tail Number')),
                ('assigned_flights', models.ManyToManyField(blank=True, related_name='assigned_aircraft', to='irops_app.flight', verbose_name='Assigned Flights')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'ordering': ['tail_number'],
            },
        ),
        migrations.CreateModel(
            name='AdminControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, verbose_name='Approval Date')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admins', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Control',
                'verbose_name_plural': 'Admin Controls',
                'ordering': ['-approval_date'],
            },
        ),
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guest Name')),
                ('last_comms', models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('email', 'Email'), ('lounge', 'Lounge')], max_length=10, verbose_name='Last Communication Method')),
                ('ack_status', models.CharField(choices=[('success', '✅'), ('warning', '⚠️'), ('failed', '❌')], max_length=10, verbose_name='Acknowledgment Status')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='irops_app.flight', verbose_name='Flight')),
            ],
            options={
                'verbose_name': 'Guest Acknowledgment',
                'verbose_name_plural': 'Guest Acknowledgments',
                'ordering': ['flight', 'name'],
            },
        ),
    ]
